version: '3.8'

services:
  first-app: 
    container_name: app1_metrics
    image: astanil/first_app:latest
    build: ./first-app
    ports: 
      - "5001:5000"
    restart: always
    networks:
      - app

  second-app: 
    container_name: app2_metrics
    image: astanil/second_app:latest
    build: ./second-app
    ports: 
      - "5002:5000"
    restart: always
    networks:
      - app
 
  nginx:
    container_name: nginx
    image: nginx:latest
    ports: 
      - "80:80"
    restart: always
    healthcheck:
      test: ["CMD" ,"curl", "-f", "http://localhost/health-check"]
      timeout: 20s
      retries: 10
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - first-app
      - second-app
    networks:
      - app

networks:
  app: