name: CI/CD

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - name: Git-checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Lint flake8
        uses: py-actions/flake8@v2

  build_and_push:
    runs-on: ubuntu-latest
    name: Build_and_push
    needs: Lint
    strategy:
      matrix:
        REQUEST: ["http://localhost/health-check:5001", "http://localhost/health-check:5002"]
    steps:
      - name: Git-checkout
        uses: actions/checkout@v4

      - name: Docker hub login
        uses: docker/login-action@v3
        with: 
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build docker-compose
        run: docker compose up -d --no-deps

      - name: Health-check
        run: curl -f ${{ matrix.REQUEST }}
          

      - name: Push first
        uses: docker/build-push-action@v3
        with:
          context: ./first-app
          push: true
          tags: |
            astanil/first_app:latest

      - name: Push second
        uses: docker/build-push-action@v3
        with:
          context: ./second-app
          push: true
          tags: |
            astanil/second_app:latest
